# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 5ee07e47-e52a-41d9-8948-3a2ea8894d48-capi-aws-check
  namespace: 5ee07e47-e52a-41d9-8948-3a2ea8894d48
spec:
  template:
    metadata:
      name: 5ee07e47-e52a-41d9-8948-3a2ea8894d48-capi-aws
    spec:
      serviceAccountName: 5ee07e47-e52a-41d9-8948-3a2ea8894d48-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 5ee07e47-e52a-41d9-8948-3a2ea8894d48
        - 5ee07e47-e52a-41d9-8948-3a2ea8894d48
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 5ee07e47-e52a-41d9-8948-3a2ea8894d48-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
